updated tag

diff --git a/.github/workflows/api-check.yml b/.github/workflows/api-check.yml
--- a/.github/workflows/api-check.yml
+++ b/.github/workflows/api-check.yml
@@ -64,25 +64,29 @@ jobs:
         key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/gst/vcpkg.json') }}
 
     - name: Install vcpkg
-      if: steps.cache_status.outputs.cache-hit == 'false'
+      if: steps.cache_status.outputs.cache-hit != 'true'
       shell: cmd
       run: |
         git clone https://github.com/microsoft/vcpkg.git
         cd vcpkg && .\bootstrap-vcpkg.bat  && cd ../
 
     - name: Install dependencies
-      if: steps.cache_status.outputs.cache-hit == 'false'
+      if: steps.cache_status.outputs.cache-hit != 'true'
       shell: cmd
       run: |
         dir
         vcpkg.exe install --x-install-root ${{ github.workspace }}\vcpkg_installed --x-manifest-root ${{ github.workspace }}\gst
 
     - name: Cache dependencies
-      if: steps.cache_status.outputs.cache-hit == 'false'
+      if: steps.cache_status.outputs.cache-hit != 'true'
       uses: actions/cache/save@v4
       with:
         path: ${{ github.workspace }}\vcpkg_installed
         key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/gst/vcpkg.json') }}
+
+    - name: Setup gendc-python
+      run: |
+        pip install gendc-python
 
     - name: Build gst-plugin
       shell: cmd
@@ -109,7 +113,37 @@ jobs:
         else
           echo 'FAILED GST single fram test with 6 components'
           exit 1
-        fi      
+        fi  
+
+  build-ubuntu:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v4.1.1
+    - name: Install dependencies
+      run: | 
+        pip3 install meson==1.1.0 ninja
+        sudo apt update
+        apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
+    - name: Build gst-plugin
+      run: |
+        meson setup --prefix ${{ github.workspace }}/install/gendc build -Dgst-plugin=enabled
+    - name: Install gst-plugin
+      run: |
+        cd build
+        ninja install
+    - name: Setup gendc-python
+      run: |
+        pip install gendc-python
+    - name: Test gst-plugin
+      run: |
+        export GST_PLUGIN_PATH=${{ github.workspace }}/install/gendc/lib/x86_64-linux-gnu/gstreamer-1.0:$GST_PLUGIN_PATH
+        if python ${{ github.workspace }}/gst/test/single_frame_test.py -i ${{ github.workspace }}/test/generated_stub/output.bin -o output -n 6; then
+          echo 'PASSED GST single fram test with 6 components'
+        else
+          echo 'FAILED GST single fram test with 6 components'
+          exit 1
+        fi  
 
   test:
     runs-on: ubuntu-latest
