updated cache

diff --git a/.github/workflows/api-check.yml b/.github/workflows/api-check.yml
--- a/.github/workflows/api-check.yml
+++ b/.github/workflows/api-check.yml
@@ -61,28 +61,28 @@ jobs:
       uses: actions/cache@v4
       with:
         path: ${{ github.workspace }}\vcpkg_installed
-        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
+        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/gst/vcpkg.json') }}
 
     - name: Install vcpkg
-      if: steps.cache_status.outputs.cache-hit != 'true'
+      if: steps.cache_status.outputs.cache-hit == 'false'
       shell: cmd
       run: |
         git clone https://github.com/microsoft/vcpkg.git
         cd vcpkg && .\bootstrap-vcpkg.bat  && cd ../
 
     - name: Install dependencies
-      if: steps.cache_status.outputs.cache-hit != 'true'
+      if: steps.cache_status.outputs.cache-hit == 'false'
       shell: cmd
       run: |
         dir
         vcpkg.exe install --x-install-root ${{ github.workspace }}\vcpkg_installed --x-manifest-root ${{ github.workspace }}\gst
 
     - name: Cache dependencies
-      if: steps.cache_status.outputs.cache-hit != 'true'
+      if: steps.cache_status.outputs.cache-hit == 'false'
       uses: actions/cache/save@v4
       with:
         path: ${{ github.workspace }}\vcpkg_installed
-        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
+        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/gst/vcpkg.json') }}
 
     - name: Build gst-plugin
       shell: cmd
@@ -90,7 +90,24 @@ jobs:
         set PATH=${{env.PKG_CONFIG_INSTALL}}/pkg-config-lite-${{env.PKG_CONFIG_VERSION}}/bin;%PATH%
         set PATH=${{ github.workspace }}/vcpkg_installed/x64-windows/bin;%PATH%
         set PKG_CONFIG_PATH=${{ github.workspace }}/vcpkg_installed/x64-windows/lib/pkgconfig;%PKG_CONFIG_PATH%
-        meson setup --prefix ${{env.PKG_CONFIG_INSTALL}}/install/gendc build -Dgst-plugin=enabled
+        meson setup --prefix ${{ github.workspace }}/install/gendc build -Dgst-plugin=enabled
+
+    - name: Install gst-plugin
+      shell: cmd
+      run: |
+        cd ${{ github.workspace }}/build
+        meson install
+
+    - name: Test gst-plugin
+        set PATH=${{ github.workspace }}/gst/vcpkg_installed/x64-windows/tools/gstreamer;%PATH%
+        set GST_PLUGIN_PATH=${{ github.workspace }}/install/gendc/lib/gstreamer-1.0;%GST_PLUGIN_PATH%
+        set GST_PLUGIN_PATH=${{ github.workspace }}/gst/vcpkg_installed/x64-windows/plugins/gstreamer;%GST_PLUGIN_PATH%
+        if python ${{ github.workspace }}/gst/test/single_frame_test.py -i ${{ github.workspace }}/test/generated_stub/output.bin -o output -n 6; then
+          echo 'PASSED GST single fram test with 6 components'
+        else
+          echo 'FAILED GST single fram test with 6 components'
+          exit 1
+        fi      
 
   test:
     runs-on: ubuntu-latest
